### PR TITLE
Stream api

### LINKED ISSUE #4: Provide non-Canvas API as an alternative
`Canvas` should not be the only way to use this library. It would be more flexible to work with `Stream` and `Factory` types, while leaving the canvas API redirecting to them for convenience. See `gfx-debug-draw` for an [example](https://github.com/PistonDevelopers/gfx-debug-draw/blob/master/src/debug_renderer.rs#L46). Note: this will look better when factories start carrying their own capabilities.

### PR DESCRIPTION
**Pull request by Kagami**
- Add stream version of draw methods: `sdraw_end`, `sdraw_end_at`
- Add methods which return batches instead: `get_batch`, `get_batch_at`

Fixes #4
cc @kvark

### CODE REVIEW

**Comment by kvark** [comment]
I think the `stream` version should be the default, and `s` prefix is not too sound. `Canvas` API can follow `gfx-debug-draw` case (`draw_end_canvas`). @stjahns would you see it fit?

**Comment by Kagami** [comment]
> I think the stream version should be the default

That would be a breaking change. Not a big deal at this level of development though, so it's ok.

> Canvas API can follow gfx-debug-draw case (draw_end_canvas)

Ok, we may be consistent with `gfx-debug-draw` here.

Would like to hear @stjahns opinion too.

**Comment by Kagami** [comment]
Seems like @stjahns is quite inactive last time and one of the library users waiting for this.

I've rebased over master, made draw_end[_at] accept the stream by default and also add `canvas_` aliases instead because it's more logical IMO.

@kvark what do you think?

**Comment by kvark** [comment]
@Kagami It's a bit unfortunate to see this much boilerplate just to support `Canvas`. I believe the user would need to change less/nothing in case they need it:
1. for simple apps, like the examples here, it just adds one line to have a (`let mut stream = (&mut canvas.renderer, &convas.output);`)
2. more complex apps are not supposed to send Canvas all the way down to the rendering routines anyway.

Hence, I'm leaning towards `gfx_text` providing only `Stream` API. The burden of extracting the stream will be removed with https://github.com/gfx-rs/gfx-rs/issues/690, which would allow `gfx_text` to have its own factory.

@LaylConway - would it hurt your use case?

**Comment by Kagami** [comment]
Ok, fixed. Does it look good to you now?

@LaylConway actually _wanted_ stream API, so it should be ok.

**Comment by LaylBongers** [comment]
I'm personally of the opinion that Canvas is an unneeded abstraction now that Stream is provided. I've been using this fork so far in Phosphorus and it seems to work great for my needs.

**Comment by kvark** [comment]
@LaylConway thanks for the feedback!

**Pull request merged**
