### PR TITLE
Flexible output format support

### LINKED ISSUE #45: Only RGBA8 format supported
Neither HDR targets nor Srgba8 target are allowed. Draw is hardcoded on Rgba8.

What's the recommended workaround?

### PR DESCRIPTION
**Pull request by kvark**
Closes #45

### CODE REVIEW

**Comment by Kagami** [comment]
Thanks, @kvark!

**Comment by joelwkall** [comment]
Awesome! Any idea when this will hit crates.io?

**Comment by Kagami** [comment]
@joelwkall just published 0.11.0, try it out.

**Comment by joelwkall** [comment]
I'm probably just to green at rust, but I can't make the new function accept the Factory from my PistonWindow. 

`let mut text = gfx_text::new(window.factory.clone()).build().unwrap();`

Just gives me 

`the trait gfx_core::factory::Factory<_> is not implemented for the type gfx_device_gl::factory::Factory`

Any help appreciated.

**Comment by kvark** [comment]
Sounds like your app is linking against a different version of GFX than gfx_text is using.

**Comment by joelwkall** [comment]
Hmm, yes, piston_window seems to be using gfx 0.11, while gfx_text uses gfx 0.12. How can I fix that?

**Comment by kvark** [comment]
Submit a PR to piston_window. There are next to no changes to GFX API in the new version, so updating should be easy.

**Comment by kvark** [comment]
Alternatively, as a workaround, you can checkout fresh GFX and do a cargo override on it.

**Pull request merged**
