### PR TITLE
update to gfx 0.8

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by bvssvni** [comment]
Thanks!

**Comment by Kagami** [comment]
Thanks! Published gfx_text `0.6.0`.

**Comment by bvssvni** [comment]
@Kagami Could you use PR instead of pushing directly next time? Makes it easier to know what's happening since I get an email about the update. Then I can re-run Eco to check everything is alright.

**Comment by Kagami** [comment]
Ok, no problem.

**Comment by Kagami** [comment]
@bvssvni do you prefer all commits to be landed via PR or just significant changes? It's a bit routine to create PR for e.g. every trivial change in readme.

**Comment by bvssvni** [comment]
@Kagami There is a direct push feature where you can make a PR from a temporary branch.

**Comment by Kagami** [comment]
@bvssvni elaborate please? Do you mean some feature of GitHub which can be enabled in project settings?

**Comment by bvssvni** [comment]
@Kagami When editing the README, you get two choices beside the commit button. One of them is to create another branch and do a PR.

**Comment by Kagami** [comment]
Ok, I tested it a bit and PRs for features are ok, but I think creating PR just for version bump is wrong.
- git tag should point to exact commit, not to the merge
- cargo publish should be made from exact same commit as git tag
- version should be bumped only after everything was tested (e.g. docs, README formatting, etc), so it can't be part of another PR; and creating PR only for single line change is pointless

**Comment by bvssvni** [comment]
@Kagami We need a solution that doesn't require much work over time. Currently we do a PR for bumping versions (so people get an email), and use Eco to tell us the libraries that needs update. If you want to discuss this, please open up an issue on the piston repo.

**Pull request merged**
